### ISSUE TITLE
ARMED_HOME is reflected in the home-assistant UI as ‘Armed away’.

### ISSUE THREAD

**Issue by nickw444** [nickw444/nessclient#35]
Ref: https://community.home-assistant.io/t/ness-dx8-dx16-alarm/23285/168?u=nickw444

**Comment by cryptelli** [comment]
I was going to ask for this as feature request, nice to see you've picked up on it 👍. Mostly use `AWAY` when arming but would be nice to have it reflect correctly.

**Comment by nickw444** [comment]
Fixed by #53  and #47
